import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    { type: 'autogenerated', dirName: '.' },
    'concepts',
    {
      type: 'category',
      label: 'Ecosystem',
      collapsed: false,
      collapsible: false,
      items: [
        {
          type: 'link',
          href: 'https://docs.smith.langchain.com/',
          label: '🦜🛠️ LangSmith',
        },
        {
          type: 'link',
          href: 'https://langchain-ai.github.io/langgraphjs/',
          label: '🦜🕸️ LangGraph.js',
        },
      ],
    },
  ],
};
export default sidebars;
