name: 'Auto Assign'

on:
  pull_request:
    types: opened

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    permissions: # 권한 설정
      pull-requests: write # PR 쓰기 권한 설정
    steps:
      - uses: kentaro-m/auto-assign-action@v2.0.0